// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/contacts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/contacts.get').default>>>>
    }
    '/api/admin/contacts/:id/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/contacts/[id]/delete.post').default>>>>
    }
    '/api/admin/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/posts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/posts.post').default>>>>
    }
    '/api/admin/posts/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/posts/[id].get').default>>>>
    }
    '/api/admin/posts/:id/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/posts/[id]/delete.post').default>>>>
    }
    '/api/admin/posts/:id/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/posts/[id]/update.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/comments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comments/index.post').default>>>>
    }
    '/api/contact': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact/index.post').default>>>>
    }
    '/api/posts/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[slug].get').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags.get').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}